export const dashboardOverviewData = {
  summary: [
    {
      id: "active-services",
      label: "Active services",
      value: "5",
      detail: "2 production ready",
    },
    {
      id: "healthy-services",
      label: "Healthy",
      value: "4/5",
      detail: "Redis needs attention",
    },
    {
      id: "monthly-spend",
      label: "Monthly spend",
      value: "$72.40",
      detail: "Projected for this month",
    },
    {
      id: "storage-used",
      label: "Storage used",
      value: "138 GB",
      detail: "Across all services",
    },
  ],
  services: [
    {
      id: "postgres-main",
      name: "app-postgres-main",
      type: "PostgreSQL",
      status: "Healthy",
      plan: "Production",
      region: "Singapore",
      version: "16.3",
      cpuUsage: 38,
      memoryUsage: 52,
      storageUsage: 64,
      connection: "Ready",
      backups: "Hourly, 7 day retention",
      lastUpdated: "2 min ago",
    },
    {
      id: "redis-cache",
      name: "api-redis-cache",
      type: "Redis",
      status: "Attention",
      plan: "Starter",
      region: "Singapore",
      version: "7.2",
      cpuUsage: 71,
      memoryUsage: 84,
      storageUsage: 42,
      connection: "Ready",
      backups: "Snapshots disabled",
      lastUpdated: "5 min ago",
    },
    {
      id: "clickhouse-events",
      name: "events-clickhouse",
      type: "ClickHouse",
      status: "Planned",
      plan: "Preview",
      region: "Tokyo",
      version: "24.x",
      cpuUsage: 0,
      memoryUsage: 0,
      storageUsage: 0,
      connection: "Not provisioned",
      backups: "Available after provisioning",
      lastUpdated: "Roadmap",
    },
    {
      id: "object-storage",
      name: "media-object-storage",
      type: "Object Storage",
      status: "Planned",
      plan: "Preview",
      region: "Singapore",
      version: "S3 compatible",
      cpuUsage: 0,
      memoryUsage: 0,
      storageUsage: 0,
      connection: "Not provisioned",
      backups: "Versioning planned",
      lastUpdated: "Roadmap",
    },
    {
      id: "message-queue",
      name: "jobs-message-queue",
      type: "Queue",
      status: "Planned",
      plan: "Preview",
      region: "Singapore",
      version: "RabbitMQ compatible",
      cpuUsage: 0,
      memoryUsage: 0,
      storageUsage: 0,
      connection: "Not provisioned",
      backups: "Durable queues planned",
      lastUpdated: "Roadmap",
    },
  ],
  nextActions: [
    "Rotate Redis password after memory pressure is resolved.",
    "Enable hourly PostgreSQL backup restore testing.",
    "Provision ClickHouse when event ingestion is ready.",
  ],
} as const;
